/* Generated By:JJTree&JavaCC: Do not edit this line. CompiladorConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TIPOINTEIRO = 6;
  /** RegularExpression Id. */
  int TIPOBOOL = 7;
  /** RegularExpression Id. */
  int TIPOSTRING = 8;
  /** RegularExpression Id. */
  int INICIOPROGRAMA = 9;
  /** RegularExpression Id. */
  int ABREBLOCO = 10;
  /** RegularExpression Id. */
  int FIMBLOCO = 11;
  /** RegularExpression Id. */
  int ABREBLOCOND = 12;
  /** RegularExpression Id. */
  int FECHABLOCOND = 13;
  /** RegularExpression Id. */
  int CONDIF = 14;
  /** RegularExpression Id. */
  int CONDELSE = 15;
  /** RegularExpression Id. */
  int REPWHILE = 16;
  /** RegularExpression Id. */
  int REPFOR = 17;
  /** RegularExpression Id. */
  int ENTAO = 18;
  /** RegularExpression Id. */
  int NUMERO = 19;
  /** RegularExpression Id. */
  int DIGITO = 20;
  /** RegularExpression Id. */
  int ID = 21;
  /** RegularExpression Id. */
  int LETRA = 22;
  /** RegularExpression Id. */
  int ASPAS = 23;
  /** RegularExpression Id. */
  int VIRGULA = 24;
  /** RegularExpression Id. */
  int DIFERENTE = 25;
  /** RegularExpression Id. */
  int MENORIGUAL = 26;
  /** RegularExpression Id. */
  int MAIORIGUAL = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int E = 29;
  /** RegularExpression Id. */
  int OU = 30;
  /** RegularExpression Id. */
  int MAIS = 31;
  /** RegularExpression Id. */
  int MENOS = 32;
  /** RegularExpression Id. */
  int MULTI = 33;
  /** RegularExpression Id. */
  int DIV = 34;
  /** RegularExpression Id. */
  int MAIOR = 35;
  /** RegularExpression Id. */
  int MENOR = 36;
  /** RegularExpression Id. */
  int ATRIBUI = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\"tipo\"",
    "\"busao\"",
    "\"vei\"",
    "\"bora\"",
    "\"cola aqui\"",
    "\"flw\"",
    "\"vamo\"",
    "\"vlw\"",
    "\"se pa\"",
    "\"nem fudendo\"",
    "\"mano\"",
    "\"mano do ceu\"",
    "\"parsa\"",
    "<NUMERO>",
    "<DIGITO>",
    "<ID>",
    "<LETRA>",
    "\"\\\'\"",
    "\",\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
  };

}
