/* Generated By:JavaCC: Do not edit this line. CompiladorTreeConstants.java Version 5.0 */
package parser;

public interface CompiladorTreeConstants
{
  public int JJTTIPOINTEIRO = 0;
  public int JJTTIPOBOOL = 1;
  public int JJTTIPOSTRING = 2;
  public int JJTNUMERO = 3;
  public int JJTID = 4;
  public int JJTASPAS = 5;
  public int JJTVIRGULA = 6;
  public int JJTCONDIF = 7;
  public int JJTCONDELSE = 8;
  public int JJTREPWHILE = 9;
  public int JJTREPFOR = 10;
  public int JJTENTAO = 11;
  public int JJTMAIS = 12;
  public int JJTMENOS = 13;
  public int JJTMULTI = 14;
  public int JJTDIV = 15;
  public int JJTMAIOR = 16;
  public int JJTMENOR = 17;
  public int JJTATRIBUI = 18;
  public int JJTINICIOPROGRAMA = 19;
  public int JJTABREBLOCO = 20;
  public int JJTFIMBLOCO = 21;
  public int JJTABREBLOCOND = 22;
  public int JJTFECHABLOCOND = 23;
  public int JJTDIFERENTE = 24;
  public int JJTMENORIGUAL = 25;
  public int JJTMAIORIGUAL = 26;
  public int JJTIGUAL = 27;
  public int JJTE = 28;
  public int JJTOU = 29;
  public int JJTMAIN = 30;
  public int JJTTIPODADO = 31;
  public int JJTTIPO_CALCULO = 32;
  public int JJTTIPOCOMPARACAO = 33;
  public int JJTTIPOOPERADORLOGICO = 34;
  public int JJTCORPO = 35;
  public int JJTINPUT = 36;
  public int JJTDEFINEVARIAVEIS = 37;
  public int JJTATRIBUICAOVAR = 38;
  public int JJTCOND = 39;
  public int JJTSETCOND = 40;


  public String[] jjtNodeName = {
    "tipoInteiro",
    "tipoBool",
    "tipoString",
    "numero",
    "id",
    "aspas",
    "virgula",
    "condIf",
    "condElse",
    "repWhile",
    "repFor",
    "entao",
    "mais",
    "menos",
    "multi",
    "div",
    "maior",
    "menor",
    "atribui",
    "inicioPrograma",
    "abreBloco",
    "fimBloco",
    "abreBloCond",
    "fechaBloCond",
    "diferente",
    "menorIgual",
    "maiorIgual",
    "igual",
    "e",
    "ou",
    "main",
    "tipoDado",
    "tipo_Calculo",
    "tipoComparacao",
    "tipoOperadorLogico",
    "corpo",
    "input",
    "defineVariaveis",
    "atribuicaoVar",
    "cond",
    "setCond",
  };
}
/* JavaCC - OriginalChecksum=55a617809cd14b26ba8a8408cde7885a (do not edit this line) */
